Create group model
yukitohiroki/chat-space pull request #6
Opened 2019-01-19 12:22 UTC by yukitohiroki

# WHAT
   グループ作成機能の実装
# WHY
   チャット画面にてグループ作成を可能にするため

2019-01-19 12:33 UTC, ghost requested changes

2019-01-19 12:33 UTC, hiroki5123 commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
アンパサンド使いたいです

2019-01-19 12:33 UTC, hiroki5123 commented on app/controllers/groups_controller.rb
> +    set_group
ここbefore_actionで呼び出してるので不要だと思うのですが。。。

2019-01-19 12:33 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +      render :deit
ここタイポですか？

2019-01-19 12:43 UTC, yukitohiroki commented on app/controllers/users_controller.rb
> +      render :deit
修正しました
タイポの意味調べましたw

2019-01-19 12:43 UTC, yukitohiroki commented on app/controllers/groups_controller.rb
> +    set_group
修正しました

2019-01-19 12:46 UTC, yukitohiroki commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
試しにやってみたら、CSSがうまく適用
.chat-group-form {
  width: 980px;
  margin: 60px auto;
  padding: 40px;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 5px;
  box-sizing: border-box;

  h1 {
    letter-spacing: 2px;
    font-size: 24px;
    font-weight: bold;
    text-align: center;
  }

  &__chat-group-form__errors {

何がダメなんですかね？

2019-01-19 12:47 UTC, yukitohiroki commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
CSS上手く適用されませんでした

2019-01-20 05:07 UTC, hiroki5123 commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
アンパサンドの使い方が間違っています。
ここでアンパサンドを使うためには、

.chat-group-form{
  width:900px;
 ~~~
   &__errors {
    ~~~
  }
}

みたいな感じで書きます

2019-01-20 05:17 UTC, yukitohiroki commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
修正しました ちなみに他の箇所も同様に修正出来ます？
  .chat-group-form__field {
    margin-top: 30px;
    &:after {
      content: "";
      clear: both;
      display: block;
    }

    .chat-group-form__field--left {
      float: left;
      width: 30%;
      padding-right: 20px;
      padding-left: 20px;
      box-sizing: border-box;
    }

    .chat-group-form__field--right {
      float: right;
      width: 70%;
    }

    .chat-group-form__label {
      display: block;
      line-height: 50px;
      font-weight: bold;
      text-align: right;
    }

    .chat-group-form__input {
      float: left;
      width: 100%;
      line-height: 30px;
      padding: 10px 15px;
      box-sizing: border-box;
    }
  }

  .chat-group-user {
    padding: 0 15px;
    line-height: 50px;
    font-size: 14px;
    border-bottom: 1px solid #ddd;
    &:after {
      content: "";
      clear: both;
      display: block;
    }

    .chat-group-user__name {
      float: left;
    }

    .chat-group-user__btn {
      float: right;
      display: inline-block;
      cursor: pointer;

      &.chat-group-user__btn--add {
        color: #38aef0;
      }

      &.chat-group-user__btn--remove {
        color: #f05050;
      }
    }
  }

  .chat-group-form__action-btn {
    display: inline-block;
    padding: 12px 20px;
    color: #fff;
    background-color: #38aef0;
    border: 0;
  }
}

2019-01-20 05:19 UTC, yukitohiroki commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
chat-group-formとchat-group-userをアンパサンドにする感じです

2019-01-20 05:23 UTC, ghost commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
他の場所もできると思います。
もしアンパサンドの使い方がわからなければ、TECH::CONNECTにてご質問ください。

2019-01-20 07:43 UTC, hiroki5123 commented
修正したらpushしてくださいー

2019-01-20 07:47 UTC, yukitohiroki commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
調べて以下のように修正してみましたがいかがでしょうか
.chat-group-form {
$parent: &;
width: 980px;
margin: 60px auto;
padding: 40px;
background-color: #fff;
border: 1px solid #ddd;
border-radius: 5px;
box-sizing: border-box;

h1 {
letter-spacing: 2px;
font-size: 24px;
font-weight: bold;
text-align: center;
}

&__errors {
margin: 30px 0;
padding: 20px 40px;
border: 1px solid #ddd;
border-radius: 2px;
text-align: center;

h2 {
margin-bottom: 10px;
color: #f05050;
font-size: 14px;
}

ul {
margin: 0;
padding: 0;
list-style: none;
}

li {
margin: 0;
padding: 0;
font-size: 13px;
}
}

&__field {
margin-top: 30px;
&:after {
content: "";
clear: both;
display: block;
}

#{$parent}__field--left {
float: left;
width: 30%;
padding-right: 20px;
padding-left: 20px;
box-sizing: border-box;
}

#{$parent}__field--right {
float: right;
width: 70%;
}

#{$parent}__label {
display: block;
line-height: 50px;
font-weight: bold;
text-align: right;
}

#{$parent}__input {
float: left;
width: 100%;
line-height: 30px;
padding: 10px 15px;
box-sizing: border-box;
}
}

.chat-group-user {
$parent1: &;
padding: 0 15px;
line-height: 50px;
font-size: 14px;
border-bottom: 1px solid #ddd;
&:after {
content: "";
clear: both;
display: block;
}

&__name {
float: left;
}

&__btn {
float: right;
display: inline-block;
cursor: pointer;

#{$parent1}__btn--add {
color: #38aef0;
}

#{$parent1}__btn--remove {
color: #f05050;
}
}
}

#{$parent}__action-btn {
display: inline-block;
padding: 12px 20px;
color: #fff;
background-color: #38aef0;
border: 0;
}
}

2019-01-20 08:26 UTC, ghost commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
それでビューが正常に表示されていれば大丈夫だと思います。

2019-01-20 08:30 UTC, yukitohiroki commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
正常に表示されていますので、マージします。

2019-01-20 08:32 UTC, merged