Create-message-asynchronous
yukitohiroki/chat-space pull request #9
Opened 2019-02-03 12:34 UTC by yukitohiroki

メッセージ送信機能に非同期通信を実装

2019-02-03 12:39 UTC, ghost requested changes

2019-02-03 12:39 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +      format.html { redirect_to group_messages_path(params[:group_id])  }
インデントずれています

2019-02-03 12:39 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +    var html = `<div class="message">
画像がある時とないときで条件分岐をしましょう

2019-02-03 12:40 UTC, hiroki5123 commented
マイグレーションファイル削除してますが大丈夫ですか？

2019-02-03 12:47 UTC, yukitohiroki commented on app/controllers/messages_controller.rb
> +      format.html { redirect_to group_messages_path(params[:group_id])  }
修正しました

2019-02-03 14:03 UTC, yukitohiroki commented on app/assets/javascripts/message.js
> +    var html = `<div class="message">
修正しました

マイグレーションファイルは1回chat-spaceフォルダを誤って削除してしまったので、
gitcloneしたら既にデータベースが作成済みだったのでエラーとなりました。
それを回避するために削除した感じです。

2019-02-04 02:01 UTC, hzak2xx approved these changes
LGTMです

2019-02-04 12:10 UTC, merged